version: 2
jobs:
  prebuild:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v4-dependencies-{{ .Branch }}
            - v4-dependencies-master
            - v4-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: |
          npm test
      - store_test_results:
          path: ./reports
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v4-dependencies-{{ .Branch }}
            - v4-dependencies-master
            - v4-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npx semantic-release

workflows:
  version: 2
  build:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
          filters:
            branches:
              only:
                - /^(0|[1-9][0-9]*)(?:\.(0|[1-9][0-9]*|x))?\.x$/
                - master
                - next
                - next-major
                - beta
                - alpha
