version: 2
jobs:
  prebuild:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package-lock.json" }}
            - v3-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package-lock.json" }}
      - run: |
          npm test
      - store_test_results:
          path: ./reports
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package-lock.json" }}
            - v3-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package-lock.json" }}
      - run: npx semantic-release

workflows:
  version: 2
  build:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild
          filters:
            branches:
              only:
                - master
